### ISSUE TITLE
Неправильно построено предложение

### ISSUE THREAD

**Issue by goodmit** [kalimatas/go-tour-ru#12]
Context: https://go-tour-ru-ru.appspot.com/basics/15

Одно из предложений в описании констант на страничке тура 15/17 про константы имеет лишнее слово.
"Константы могут быть иметь символьные, строковые, булевые или числовые значения."
"могут быть иметь"

**Comment by oshliaer** [comment]
@goodmit, в тексте на момент последнего реквеста нет сочетания таких слов.

**Comment by oshliaer** [comment]
Нет такого сочетания слов в тексте.
