### ISSUE TITLE
tour: 

### ISSUE THREAD

**Issue by nbk-kolyan** [kalimatas/go-tour-ru#17]
Context: https://go-tour-ru-ru.appspot.com/basics/3

just run the program in editor - "Error communicating with remote server."
Probably its because selecting ru language. See url - "ru-ur" probably problem here

**Comment by nbk-kolyan** [comment]
fixed by reset button, but by default server not responding

**Comment by kalimatas** [comment]
I guess the issue is with free hosting on GAE: if server is not used for some time, then for the first request there will be some delay, because GAE needs to warm up the BE.
