### ISSUE TITLE
Как понять условие задачи https://go-tour-ru-ru.appspot.com/moretypes/18?

### ISSUE THREAD

**Issue by patsevanton** [kalimatas/go-tour-ru#25]
Как понять условие задачи https://go-tour-ru-ru.appspot.com/moretypes/18 ?
функцию написал так.
```
package main

import "golang.org/x/tour/pic"

array = [][]uint8

func Pic(dx, dy int) [][]uint8 {
    for i:=0; i < dy; i++ {
      array[i] = dx
  }
  return array
}

func main() {
  pic.Show(Pic)
}
```

Непонята фраза "Выбор изображения за вами. Среди интересных функций (x+y)/2, x*y и x^y.
Спасибо.

**Comment by kalimatas** [comment]
Функция `Pic` возвращает срез срезов, что по сути двумерный массив. Каждый элемент этой структуры данных это значение типа `unit8`, которое будет интерпретировато как оттенок синего цвета. "Выбор изображения за вами." с примерами фукнций означает, что в зависимости от того, как будет получены значения этого думерного массива, в результате будут отрисованы различные изображения.

Например, с функцией `(x+y)/2`, код можно написать так:
```
func Pic(dx, dy int) [][]uint8 {
    pic := make([][]uint8, dy)
    for y := range pic {
        pic[y] = make([]uint8, dx)
        for x := range pic[y] {
            pic[y][x] = uint8( (x+y)/2 )
        }
    }
    return pic
}
```

Тогда в результате получится градиент.
