### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by llkk4346** [kalimatas/go-tour-ru#26]
Context: https://go-tour-ru-ru.appspot.com/moretypes/11
Если возможно, то необходимо поправить перевод в русской версии.
The capacity of a slice is the number of elements in the 
underlying array, counting from the first element in the slice.

Слово underlying переведено как нижележащий, хотя более правильный вариант перевода будет звучать как основной. Просто перевод, который предложен сейчас вызывает некоторые трудности с пониманием для людей проходящих курс на русском.

**Comment by kalimatas** [comment]
Спасибо! Я заменил "нижележащий" на "лежащий в основе", т.к. "основной" на мой взгляд тоже не совсем корректный перевод.
