### ISSUE TITLE
tour: mistake in russian version of tour

### ISSUE THREAD

**Issue by AndreyMonastyrskiy** [kalimatas/go-tour-ru#37]
Context: https://go-tour-ru-ru.appspot.com/basics/3
In the Russian code example, "pi" is already written with a capital "P" letter, which contradicts the example in which you want to change the letter from small to capital.
What in example: "fmt.Println(math.Pi)"
What expected: "fmt.Println(math.pi)"

**Comment by kalimatas** [comment]
It matches English version https://tour.golang.org/basics/3.
