### ISSUE TITLE
tour: t, ok := i.(T) для типов, которые не подходят интерфейсу

### ISSUE THREAD

**Issue by kirill-d-lappo** [kalimatas/go-tour-ru#38]
Context: https://go-tour-ru-ru.appspot.com/methods/15

Я бы здесь еще уточнил про такйо момент
```golang
package main

import "fmt"

type ICommand interface {
	Execute()
}

type Person struct {
	Name string
}

func (p Person) Execute() {
	fmt.Println("Person - Execute")
}

func main() {
	var command ICommand = Person{Name: "Harry"}

	// main.go:32:21: impossible type assertion:
	// int does not implement ICommand (missing Execute method)
	value, ok := command.(int)
}
```

Похоже, что если речь идет не про обобщенный интерфейс `interface{}`, то ошибка упадет в любом случае, даже если делать проверку с помощью `value, ok := server.(int)`

---
go version go1.13.4 windows/amd64

**Comment by kalimatas** [comment]
@Kira-Lappo, я стараюсь быть максимально близко к оригиналу https://tour.golang.org/methods/15.
