### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by Gbug512** [kalimatas/go-tour-ru#39]
Context: https://go-tour-ru-ru.appspot.com/basics/3

Change the title above to describe your issue and add your feedback here, including code if necessary

https://go-tour-ru-ru.appspot.com/basics/3

./prog.go:9:14: cannot refer to unexported name math.pi
./prog.go:9:14: undefined: math.pi

**Comment by kalimatas** [comment]
Expected. Check the description of the chapter "Запустите код. Обратите внимание на сообщение об ошибке.".
