### ISSUE TITLE
tour: Изменение синтаксиса предложения

### ISSUE THREAD

**Issue by NikolasMelui** [kalimatas/go-tour-ru#40]
Context: https://go-tour-ru-ru.appspot.com/basics/11

Последнее предложение:
Когда вам надо целочисленное значение, то следует использовать int, если у вас нет особой причины использовать целочисленное значение конкретного размера или беззнаковое значение.

Не совсем грамотно построено предложение, думаю так будет гораздо лучше:
Когда вам необходимо целочисленное значение, следует использовать int, если у вас нет особой причины использовать целочисленное значение конкретного размера или беззнаковое значение.

**Comment by kalimatas** [comment]
Thanks! Fixed.

**Comment by NikolasMelui** [comment]
@kalimatas Чёт на сайте тож самое осталось...

**Comment by NikolasMelui** [comment]
![image](https://user-images.githubusercontent.com/15022582/81906166-e83be200-95d6-11ea-9036-726cd7d058ab.png)
