### ISSUE TITLE
tour: [wrong formula]

### ISSUE THREAD

**Issue by ye5no** [kalimatas/go-tour-ru#8]
Context: https://go-tour-ru-ru.appspot.com/flowcontrol/8

must be: 
z = z - (z*z-x) / (2*z)

**Comment by oshliaer** [comment]
Why?

This is [Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method)

**Comment by Loki69** [comment]
Вы написали формулу но не расшифровали значения.
Не спорю что математика важна но большинство не оценят ).

В предложение
"Для начала, просто повторите вычисления 10 раз и посмотрите, как близко вы к ответу для различных значений (1, 2, 3, ...)."
1)Непонятно что я должен увеличивать то-ли z то-ли x 
2) для значения 2, итерация должна быть 0.1

з.ы. спасибо за адаптацию, но конкретно на этом уроке у моих коллег возникла проблема, я просто озвучил их не понимания.

**Comment by kalimatas** [comment]
Причина в том, что я делал перевод несколько лет назад, но с тех пор, видимо, оригинальный тур был обновлен. Я пока не планирую обновлять локализацию, но принимаю MRs :)
